server:
  port: 8002
mybatis:
  type-aliases-package: com.zmh.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: springcloud-provider #修改eureka上的默认描述
    prefer-ip-address: true   #可以显示服务的IP地址

#info配置
info:
  app.name: zmh-springcloud
  company.name: blog.zmhstudy.com