server:
  port: 8001

spring:
  application:
    name: eureka_8001

eureka:
  instance:
    hostname: localhost:8001 #Eureka服务端的实列名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #如果为false,表示自己为注册中心